theme: jekyll-theme-midnight

plugins:
  - jekyll-github-metadata

locale: "en-US"

title: "AEM Tools"

description: "Better development of AEM projects with IDEA"

repository: "aemtools/aemtools"

markdown: redcarpet

sass:
  load_paths:
    - _sass
    - node_modules

google_analytics: UA-106197234-1

exclude:
  - Gemfile
  - Gemfile.lock

github: [metadata]

safe: true