theme: jekyll-theme-midnight

locale: "en-US"

title: "AEM Tools"

description: "Plugin for better development of AEM projects with IDEA"

repository: "aemtools/aemtools.github.io"

markdown: redcarpet

sass:
  load_paths:
    - _sass
    - node_modules

exclude:
  - Gemfile
  - Gemfile.lock

github: [metadata]

safe: false